name: Trigger
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger 
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{secrets.ACTIONS_TOKEN}}
          repository:  Thaiebu/Room_booking_CRUD 
          event-type: qa
